// Written in D programming language
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module util.messages;

import vibe.core.net;
import util.serialization.serializer;
import util.protocol;
import util.log;

import std.exception;
import std.stream;

enum PROTOCOL_VERSION = 10;

version(CLIENT_SIDE)
{
	enum PROTOCOL_SIDE = "Client";
} else version(SERVER_SIDE)
{
	enum PROTOCOL_SIDE = "Server";
} else
{
	static assert(false, "Specify protocol side version! CLIENT_SIDE or SERVER_SIDE");
}

interface TcpMessage
{
	void opCall(TcpConnection conn);
}

mixin ProtocolPool!(int, TcpMessage, GendocArchive,
	0, MessHello, 
	1, MessError,
	);

//=======================================================================================
// Client => Server only
interface Client2ServerMess : TcpMessage
{
	final void checkSide()
	{
		assert(PROTOCOL_SIDE == "Server", "Tried run server message on client!");
	}
}

class MessHello : Client2ServerMess
{
	uint vers = PROTOCOL_VERSION;

	void opCall(TcpConnection conn) // server side
	{
		checkSide();

		if(vers != PROTOCOL_VERSION)
		{
			writeNoticeLog("Client connected with wrong version!");
			auto stream = constructMessage!MessError("Wrong protocol version! Server side is: "~to!string(vers));
			conn.write(stream, true);
			conn.close();
		}

		auto stream = constructMessage!MessError("Successfull debug msg!");
		conn.write(stream, true);		
	}
}

class MessRequestMap : Client2ServerMess
{
	void opCall(TcpConnection conn) // server side
	{
		checkSide();

		
	}
}

// Client <= Server only
interface Server2ClientMess : TcpMessage
{
	final void checkSide()
	{
		assert(PROTOCOL_SIDE == "Client", "Tried run client message on server!");
	}
}

class MessError : Server2ClientMess
{
	string msg;

	this() {}

	this(string errorMsg)
	{
		msg = errorMsg;
	}

	void opCall(TcpConnection conn) // client side
	{
		checkSide();
		writeFatalLog(msg);
	}
}

// Client <=> Server