// Written in D programming language
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module connection;

import vibe.core.net;
import vibe.core.driver;

import util.iprotocol;
import util.messages;
import util.log;

import core.time;
import core.thread;

import std.stdio;
import std.string;
import std.conv;
import std.concurrency;

enum CONNECTION_TRIES = 5;
private
{
	Tid listenThread;
	TcpConnection shConnection;
}

void listenServerConnection(shared TcpConnection shConn, string ip, ushort port)
{
	auto conn = cast(TcpConnection)shConn;
	assert(conn.connected);
	writeNoticeLog("Connection to server established!");

	bool running = true;
	while(conn.connected && running)
	{
		//writeNoticeLog("Checking exit");
		try receiveTimeout(dur!"msecs"(1), (OwnerTerminated e) {throw e;} );
		catch(OwnerTerminated e)
		{
			running = false;
			writeNoticeLog("Terminating listen thread.");
		}

		//writeNoticeLog("Waiting data");
		if(!conn.dataAvailableForRead) continue;
		ubyte[] buff = new ubyte[cast(size_t)conn.leastSize];
		
		writeNoticeLog("Reading data");
		try
		{
			conn.read(buff);
		} catch(Exception e)
		{
			writeFatalLog("Failed to read data from connection!");
			return;
		}
		
		//writeNoticeLog("Translating data");
		TcpMessage[] msgs;
		size_t summ, rest;
		readObjects(buff, msgs, summ, rest);
		foreach(msg; msgs)
			msg(conn);	
	}
	conn.close();
}

void establishConnection(string ip, ushort port)
{
	TcpConnection conn = null;
	foreach(i; 0..CONNECTION_TRIES)
	{
		try
		{
			conn = connectTcp(ip, port);
			break;
		} catch(Exception e)
		{
			writeWarningLog("Connection failed, reconnect...");
		}
		Thread.sleep(dur!"seconds"(2));
	}
	if(conn is null) throw new Exception("Failed to connect to "~ip~":"~to!string(port));

	shConnection = conn;
	listenThread = spawn(&listenServerConnection, cast(shared)shConnection, ip, port);
}

void sendMsg(Msg, T...)(T args) 
	if(is(Msg : TcpMessage))
{
	static assert(__traits(compiles, new Msg(args)), Msg.stringof~" should implement constructor with formal parameters "~T.stringof);

	auto buff = constructMessage!Msg(args);
	synchronized(shConnection)
		shConnection.write(buff, true);
}

bool isConnected()
{
	synchronized(shConnection)
		return shConnection.connected;
}