// Written in D programming language
/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module main;

import derelict.tcod.libtcod;

import vibe.core.net;

import std.stdio;
import std.string;
import std.conv;

import core.time;
import core.thread;

enum VERSION = "0.0.1";

enum CON_W = 80;
enum CON_H = 50;

void dbg(T...)(T args)
{
	debug writeln(text(args));
}

void main(string[] args)
{
	DerelictTCOD.load();

	auto conn = connectTcp("127.0.0.1", 7);
	assert(conn.connected);

	ubyte[] sendArr = [4,8,15,16,23,42];
	conn.write(sendArr, true);
	//Thread.sleep(dur!"seconds"(1));

	ubyte[] arr = new ubyte[6];
	conn.waitForData(dur!"seconds"(1));
	conn.read(arr);
	writeln(arr);

	TCOD_console_init_root(CON_W, CON_H, "Dust & Blood v"~VERSION, false, TCOD_RENDERER_OPENGL);
	while( !TCOD_console_is_window_closed() )
	{
		TCOD_sys_check_for_event(TCOD_EVENT_KEY_PRESS, null, null);
		TCOD_console_clear(null);
		TCOD_console_set_char(null, 40, 25, '@');
		TCOD_console_flush();
	}
}

/*
WorldGenerator worldGen;

// world map panning
float wx = 0, wy = 0, curwx = 0, curwy = 0;
// mouse coordinates in world map
float mx = 0, my = 0;

void update(float elapsed, TCOD_key_t k, TCOD_mouse_t mouse) 
{
	// destination wanted
	wx = (worldGen.getWidth()-2*WIDTH) * mouse.cx / WIDTH;
	wy = (worldGen.getHeight()-2*HEIGHT) * mouse.cy / HEIGHT;
	curwx += (wx-curwx)*elapsed;
	curwy += (wy-curwy)*elapsed;
	mx = curwx + mouse.cx*2;
	my = curwy + mouse.cy*2;
	worldGen.updateClouds(elapsed);	
}


TCODColor getMapShadedColor(float worldX,float worldY,bool clouds) 
{
    // sun color 
    static TCODColor = sunCol(255,255,200);

    float wx = CLAMP(0.0f, worldGen.getWidth()-1,worldX);
    float wy = CLAMP(0.0f, worldGen.getHeight()-1,worldY);

	// apply cloud shadow
	float cloudAmount = clouds ? worldGen.getCloudThickness(wx,wy) : 0.0f;
	TCODColor col = worldGen.getInterpolatedColor(worldX,worldY);
	
	// apply sun light
    float intensity = worldGen.getInterpolatedIntensity(wx,wy);
	intensity = MIN(intensity, 1.5f-cloudAmount);
	int cr = cast(int)(intensity*cast(int)(col.r)*sunCol.r/255 );
	int cg = cast(int)(intensity*cast(int)(col.g)*sunCol.g/255 );
	int cb = cast(int)(intensity*cast(int)(col.b)*sunCol.b/255 );
	
	TCODColor col2;
	col2.r = CLAMP(0,255,cr);
	col2.g = CLAMP(0,255,cg);
	col2.b = CLAMP(0,255,cb);
	col2.r = MAX(col2.r,col.r/2);
	col2.g = MAX(col2.g,col.g/2);
	col2.b = MAX(col2.b,col.b/2);
	return col2;
}

void render() 
{
	// subcell resolution image
	static TCODImage map = TCODImage(CON_W*2,CON_H*2);
	// compute the map image
	for (int px=0; px <2*CON_W; px++) {
		for (int py=0; py <2*CON_H; py++) {
		    // world texel coordinate (with fisheye distorsion)
		    float wx = px+curwx;
		    float wy = py+curwy;
			map.putPixel(px,py,getMapShadedColor(wx,wy,true));
		}
	}
	map.blit2x(TCODConsole.root,0,0);
	
	TCODConsole.root.setDefaultForeground(TCODColor.white);
	static string biomeNames[] = [
		"Tundra","Cold desert","Grassland", "Boreal forest",
		"Temperate forest", "Tropical/Montane forest",
		"Hot desert", "Savanna", "Tropical dry forest", "Tropical evergreen forest",
		"Thorn forest"
	];
	if ( worldGen.isOnSea(mx,my) ) {
		// some information are irrelevant on sea
		TCODConsole.root.print(5,47,"Alt %5dm\n\nMove the mouse to scroll the map",
			cast(int)worldGen.getRealAltitude(mx,my)
		);
	} else {
		TCODConsole.root.print(5,47,"Alt %5dm  Prec %3dcm/sq. m/y  Temp %d deg C\nBiome : %s\nMove the mouse to scroll the map",
			cast(int)worldGen.getRealAltitude(mx,my),
			cast(int)worldGen.getPrecipitations(mx,my),
			cast(int)worldGen.getTemperature(mx,my),
			biomeNames[worldGen.getBiome(mx,my)]
		);
	}
}

int main (string[] args) 
{
	// initialize the game window
	TCODConsole.initRoot(CON_W,CON_H,"Dust&Blood v"~VERSION, false,TCOD_RENDERER_SDL);
	TCODSystem.setFps(25);
	TCODMouse.showCursor(true);
	
	bool endCredits=false;
	// generate the world with all data (rain, temperature and so on...)
	worldGen.generate(NULL);
	// compute light intensity on ground (depends on light direction and ground slope)
	static float lightDir[3] = [
        1.0f,1.0f,0.0f
    ];	
	worldGen.computeSunLight(lightDir);
	
	while (! TCODConsole.isWindowClosed()) {
		//	read keyboard

		TCOD_key_t k=TCODConsole.checkForKeypress(TCOD_KEY_PRESSED|TCOD_KEY_RELEASED);
		TCOD_mouse_t mouse=TCODMouse.getStatus();
		if ( k.vk == TCODK_PRINTSCREEN ) 
		{
			// screenshot
			if (! k.pressed ) TCODSystem.saveScreenshot(NULL);
			k.vk=TCODK_NONE;
		} else if ( k.lalt && (k.vk == TCODK_ENTER || k.vk == TCODK_KPENTER) ) 
		{
			// switch fullscreen
			if (! k.pressed ) TCODConsole.setFullscreen(!TCODConsole.isFullscreen());
			k.vk=TCODK_NONE;
		}
		// update the game
		update(TCODSystem.getLastFrameLength(),k,mouse);

		// render the game screen
		render();
		// render libtcod credits
		if (! endCredits ) endCredits = TCODConsole.renderCredits(4,4,true);
		// flush updates to screen
		TCODConsole.root.flush();
	}
	return 0;	
}
*/